import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import Hero from "~/components/Landing/Hero";
import Mission from "~/components/Landing/Mission";
import LearnSection from "~/components/Landing/Learn";
import ConnectSection from "~/components/Landing/Connect";
import BuildSection from "~/components/Landing/Build";
import Features from "~/components/Landing/Feature";
import Event from "~/components/Landing/Event";
import Testimonials from "~/components/Landing/Testimonials";
import Committment from "~/components/Landing/Commitment";
import Partners from "~/components/Landing/Partners";
import Subscribe from "~/components/Landing/Subscribe";
import Footer from "~/components/Footer";
// import Footer from "~/components/Landing/Footer";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col w-full items-center justify-center">
          <Hero></Hero>
          <Mission></Mission>
          <Features></Features>
          <Event></Event>
          <Committment></Committment>
          <Testimonials></Testimonials>
          <Partners></Partners>
          <Subscribe></Subscribe>
          <Footer></Footer>
          {/* <LearnSection></LearnSection>
          <ConnectSection></ConnectSection>
          <BuildSection></BuildSection> */}
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
